name: Frontend CI/CD

on:
  push:
    branches: [main]
    paths:
      - "ims-frontend/**"
  pull_request:
    branches: [main]
    paths:
      - "ims-frontend/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: ims-frontend/package-lock.json

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        working-directory: ./ims-frontend
        run: npm ci

      - name: Create .env file
        working-directory: ./ims-frontend
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" > .env.local
          echo "NEXT_PUBLIC_ADMIN_USER=${{ secrets.NEXT_PUBLIC_ADMIN_USER }}" >> .env.local
          echo "NEXT_PUBLIC_ADMIN_PASS=${{ secrets.NEXT_PUBLIC_ADMIN_PASS }}" >> .env.local

      - name: Build with Next.js
        working-directory: ./ims-frontend
        run: npm run build

      - name: Add .nojekyll file
        working-directory: ./ims-frontend
        run: touch out/.nojekyll

      - name: List build output (debug)
        working-directory: ./ims-frontend
        run: |
          echo "Contents of out directory:"
          ls -la out/
          echo "Checking for index.html:"
          ls -la out/index.html || echo "index.html not found!"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./ims-frontend/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
